apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: demo
  name: demo
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: 314291991123.dkr.ecr.us-east-2.amazonaws.com/demo:demo
        imagePullPolicy: Always
        name: demo
        ports:
        - containerPort: 8085
          protocol: TCP
        resources:
          requests:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
        - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
